### ISSUE TITLE
Textures missing

### ISSUE THREAD

**Issue by leetmussc** [nZombies-Time/nZombies-Rezzurrection#16]
A bunch of the textures are missing and it makes the gamemode unplayable.

**Comment by leetmussc** [comment]
When I load it says nzombies rezzurection is creating errors.

**Comment by Ethorbit** [comment]
You need content packs from the Workshop, this is just the lua stuff
NZR Pack 1: https://steamcommunity.com/sharedfiles/filedetails/?id=2214202203
NZR Pack 2: https://steamcommunity.com/workshop/filedetails/?id=2216099996
nZombies Pack 1: https://steamcommunity.com/workshop/filedetails/?id=675138912
nZombies Pack 2: https://steamcommunity.com/workshop/filedetails/?id=777195612

The errors are most likely because of the missing content too.
